// <auto-generated />
using System;
using EjercicioCodeFirstCursos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EjercicioCodeFirstCursos.Migrations
{
    [DbContext(typeof(CursosContext))]
    partial class CursosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EjercicioCodeFirstCursos.Models.Categoria", b =>
                {
                    b.Property<int>("CodCategoria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ExtensionImagen");

                    b.Property<DateTime>("Fecha");

                    b.Property<byte[]>("Imagen")
                        .IsRequired();

                    b.HasKey("CodCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("EjercicioCodeFirstCursos.Models.Curso", b =>
                {
                    b.Property<int>("CodCurso")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodCategoria");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Destacado");

                    b.Property<string>("ExtensionImagen");

                    b.Property<DateTime>("Fecha");

                    b.Property<byte[]>("Imagen")
                        .IsRequired();

                    b.HasKey("CodCurso");

                    b.HasIndex("CodCategoria");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("EjercicioCodeFirstCursos.Models.Curso", b =>
                {
                    b.HasOne("EjercicioCodeFirstCursos.Models.Categoria", "Categoria1")
                        .WithMany("Cursos")
                        .HasForeignKey("CodCategoria")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
